import React, { useState } from 'react';
import {
  AlertTriangle,
  CheckCircle2,
  X,
  Sparkles,
  Calendar,
  PlayCircle,
  BookOpen,
  FileText,
  ShieldCheck,
  History,
  Download,
} from 'lucide-react';
import { useAppStore } from '../store/useAppStore';
import { DeepLinkPayload } from '../types';
import { parseDeepLinkFromUrl } from '../utils/promptGenerator';

interface DeepLinkApprovalModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const DeepLinkApprovalModal: React.FC<DeepLinkApprovalModalProps> = ({ isOpen, onClose }) => {
  const { pendingDeepLink, setPendingDeepLink, applyDeepLinkPayload } = useAppStore();
  const [pastedUrl, setPastedUrl] = useState('');
  const [parseError, setParseError] = useState('');

  if (!isOpen) return null;

  const handleParsePastedUrl = () => {
    setParseError('');
    if (!pastedUrl.trim()) return;

    try {
      const queryPart = pastedUrl.includes('?') ? pastedUrl.substring(pastedUrl.indexOf('?')) : pastedUrl;
      const parsed = parseDeepLinkFromUrl(queryPart);
      if (parsed) {
        setPendingDeepLink(parsed);
      } else {
        setParseError('Invalid or unsupported QTickX deep-link URL format.');
      }
    } catch (err) {
      setParseError('Failed to parse URL link.');
    }
  };

  const handleConfirmApply = () => {
    if (pendingDeepLink) {
      applyDeepLinkPayload(pendingDeepLink);
      onClose();
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/75 backdrop-blur-md overflow-y-auto">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl max-w-lg w-full p-6 sm:p-7 shadow-2xl relative space-y-6 my-8 animate-in fade-in zoom-in duration-200">
        {/* Close Button */}
        <button
          type="button"
          onClick={onClose}
          className="absolute top-5 right-5 p-2 rounded-full text-slate-400 hover:text-slate-600 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800 transition-all"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Header */}
        <div className="flex items-center gap-3">
          <div className="p-3 rounded-2xl bg-gradient-to-tr from-amber-500 to-orange-600 text-white shadow-lg shadow-amber-500/20">
            <Download className="w-6 h-6" />
          </div>
          <div>
            <span className="text-[11px] font-black uppercase tracking-wider text-amber-600 dark:text-amber-400">
              Import & Safety Verification
            </span>
            <h2 className="text-xl font-black text-slate-900 dark:text-white leading-tight">
              Approve Deep Link Import
            </h2>
          </div>
        </div>

        {/* If no pending deep link, show manual URL paste input */}
        {!pendingDeepLink ? (
          <div className="space-y-4">
            <p className="text-xs text-slate-600 dark:text-slate-300">
              Paste a QTickX practice, schedule, or flashcard deep-link URL generated by AI or shared by a friend to preview and import:
            </p>

            <div className="space-y-2">
              <input
                type="text"
                value={pastedUrl}
                onChange={(e) => {
                  setPastedUrl(e.target.value);
                  setParseError('');
                }}
                placeholder="https://.../?addPractice=1&subject=Physics..."
                className="w-full px-3.5 py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-xs font-mono text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-amber-500"
              />
              {parseError && (
                <div className="text-xs text-rose-500 font-medium">{parseError}</div>
              )}
            </div>

            <button
              type="button"
              onClick={handleParsePastedUrl}
              className="w-full py-2.5 rounded-xl bg-amber-600 hover:bg-amber-700 text-white font-bold text-xs shadow-md transition-all flex items-center justify-center gap-2"
            >
              <Sparkles className="w-4 h-4" />
              <span>Parse & Preview Payload</span>
            </button>
          </div>
        ) : (
          <div className="space-y-5">
            {/* Warning Banner */}
            <div className="p-4 rounded-2xl bg-amber-50 dark:bg-amber-950/40 border border-amber-200/80 dark:border-amber-800/60 text-xs text-amber-900 dark:text-amber-200 space-y-1.5">
              <div className="flex items-center gap-2 font-bold text-amber-800 dark:text-amber-300">
                <AlertTriangle className="w-4 h-4 text-amber-600 dark:text-amber-400 shrink-0" />
                <span>Verification & Version Backup Warning</span>
              </div>
              <p className="text-[11px] leading-relaxed">
                Applying this payload will update your current app state. A <strong>safety history snapshot</strong> will be created automatically before applying, so you can easily roll back anytime!
              </p>
            </div>

            {/* Payload Preview Details */}
            <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-3">
              <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-700 pb-2">
                <span className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
                  Import Details
                </span>
                <span className="px-2.5 py-0.5 rounded-full bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300 font-bold text-[10px] uppercase">
                  {pendingDeepLink.type}
                </span>
              </div>

              <div className="space-y-2 text-xs">
                <div>
                  <span className="font-bold text-slate-900 dark:text-white">Title: </span>
                  <span className="text-slate-700 dark:text-slate-300">{pendingDeepLink.title || 'Custom Payload'}</span>
                </div>

                {pendingDeepLink.description && (
                  <div>
                    <span className="font-bold text-slate-900 dark:text-white">Description: </span>
                    <span className="text-slate-600 dark:text-slate-400">{pendingDeepLink.description}</span>
                  </div>
                )}

                {/* Practice Settings Preview */}
                {pendingDeepLink.practiceSettings && (
                  <div className="p-3 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 space-y-1">
                    <div className="font-bold text-blue-600 dark:text-blue-400 flex items-center gap-1.5 text-xs">
                      <PlayCircle className="w-3.5 h-3.5" />
                      <span>Practice Test Configuration</span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 text-[11px] text-slate-600 dark:text-slate-300 pt-1">
                      <div>Subject: <strong>{pendingDeepLink.practiceSettings.subject}</strong></div>
                      <div>Questions: <strong>{pendingDeepLink.practiceSettings.totalQuestions} Qs</strong></div>
                      <div>Target Pace: <strong>{Math.round((pendingDeepLink.practiceSettings.targetTimePerQuestion || 180) / 60)} min/Q</strong></div>
                      <div>Mode: <strong>{pendingDeepLink.practiceSettings.mode}</strong></div>
                    </div>
                  </div>
                )}

                {/* Schedule Events Preview */}
                {pendingDeepLink.scheduleEvents && pendingDeepLink.scheduleEvents.length > 0 && (
                  <div className="p-3 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 space-y-1">
                    <div className="font-bold text-purple-600 dark:text-purple-400 flex items-center gap-1.5 text-xs">
                      <Calendar className="w-3.5 h-3.5" />
                      <span>{pendingDeepLink.scheduleEvents.length} Exam Schedule Events</span>
                    </div>
                    <ul className="text-[11px] text-slate-600 dark:text-slate-300 list-disc list-inside space-y-0.5">
                      {pendingDeepLink.scheduleEvents.slice(0, 3).map((ev, i) => (
                        <li key={i}>[{ev.date}] {ev.code} ({ev.subject}): {ev.syllabus}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Flashcards Preview */}
                {pendingDeepLink.flashcards && pendingDeepLink.flashcards.length > 0 && (
                  <div className="p-3 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 space-y-1">
                    <div className="font-bold text-emerald-600 dark:text-emerald-400 flex items-center gap-1.5 text-xs">
                      <BookOpen className="w-3.5 h-3.5" />
                      <span>{pendingDeepLink.flashcards.length} Formula Flashcards</span>
                    </div>
                    <div className="text-[11px] text-slate-600 dark:text-slate-300">
                      Topics: {pendingDeepLink.flashcards.map(f => f.topic).join(', ')}
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex items-center justify-end gap-3 pt-2">
              <button
                type="button"
                onClick={() => {
                  setPendingDeepLink(null);
                  onClose();
                }}
                className="px-4 py-2.5 rounded-xl border border-slate-200 dark:border-slate-800 hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300 text-xs font-bold transition-all"
              >
                Cancel / Reject
              </button>
              <button
                type="button"
                onClick={handleConfirmApply}
                className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white text-xs font-black shadow-lg shadow-emerald-500/25 flex items-center gap-2 transition-all"
              >
                <ShieldCheck className="w-4 h-4" />
                <span>Approve & Apply Payload</span>
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
